In [1]:
%matplotlib inline

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

### 矩陣相加

In [2]:
m1 = np.random.randint(1, 100, size=(3, 3))
m2 = np.random.randint(1, 100, size=(3, 3))

In [3]:
def matrix_plus(m1, m2):
    return m1 + m2

print("第一個矩陣為:\n", m1)
print("第二個矩陣為:\n", m2)
print("兩個矩陣相加為:\n", matrix_plus(m1, m2))

第一個矩陣為:
 [[ 2 56 63]
 [41 23 10]
 [28 29 32]]
第二個矩陣為:
 [[69 95 51]
 [55 51 50]
 [43  8 44]]
兩個矩陣相加為:
 [[ 71 151 114]
 [ 96  74  60]
 [ 71  37  76]]
